### ISSUE TITLE
Pages and searches don't work

### ISSUE THREAD

**Issue by FireMasterK** [zedeus/nitter#194]
Most of the time, user pages and searches don't work on my instance, could this be some sort of rate-limiting?
I'm using the published docker image docker.
![image](https://user-images.githubusercontent.com/20838718/85105354-02955b00-b228-11ea-87e9-b6303b80a2c7.png)

**Comment by zedeus** [comment]
This should be fixed in the latest commit. The issue has been a bit weird to pin down due to the long waiting times required, but it seems tokens expire if you don't use them for ~1 hour, while they normally expire after 3 hours. Keeping track of this now, the issue shouldn't happen for low activity instances anymore

**Comment by FireMasterK** [comment]
Can confirm it works now.
