### ISSUE TITLE
http for rss?

### ISSUE THREAD

**Issue by somedevreally** [zedeus/nitter#223]
Hello,

i have nitter docker hosted locally with http only. 
but when i add any nitter rss to tt-rss the feed url/image is automatically converts to https
is there any configuration i need to add or change? 

thanks

**Comment by awt** [comment]
I have to re-apply a patch each time I update so I can run nitter on my local machine w/o worrying about all the https cert nonsense.

**Comment by Foxtrek64** [comment]
Fwiw guys, if this is strictly internal, [generating a self signed certificate](https://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl) (stackoverflow.com) is trivial. If it's external-facing at all, using [certbot](https://certbot.eff.org/) (certbot.eff.org) to generate a free cert is even easier since certbot will install the certificate for you and configure your web server to use it.

If you go the first option, you can give yourself a few years on your certificate so you don't have to worry about it expiring. I forget what that term is since they just changed it, but even a year should be sufficient time for dev/test.

Here's the command line for a self-signed cert if you don't want to open the SO link:

```
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
```

**Comment by somedevreally** [comment]
apologies for delayed reply. 
ok so i generated the cert and key, how do i configure it in docker-compose?
thanks

**Comment by Foxtrek64** [comment]
I'm not that familiar with docker honestly, but the wiki shows some examples on setting up reverse proxies for Apache and Nginx. Perhaps those will be of use to you?

**Comment by somedevreally** [comment]
thank you works perfectly.
