### ISSUE TITLE
Cannot use the multi-feed feature when adding over 20 accounts.

### ISSUE THREAD

**Issue by dreamscapeDistance** [zedeus/nitter#310]
Hi,

I was looking forward to ditching Twitter completely, and to substitute it with Nitter's multi-feed feature. However I cannot add more than 20 accounts or I get thrown an error that says "_no items found_".

Is this a bug?
Thanks :)

**Comment by zedeus** [comment]
This is unfortunately not a bug, it's due to how multi-feeds are implemented, combined with Twitter's search query length limit. Once you go above ~20 accounts, the search query passes the ~500 character limit, and you get "not found". There are some solutions to this, which are also required to support the account system in the future, but I'm not sure when I'll have time to work on it. If you're fine with using an RSS client, you can just make multiple multi-feeds.

**Comment by dreamscapeDistance** [comment]
> This is unfortunately not a bug, it's due to how multi-feeds are implemented, combined with Twitter's search query length limit. Once you go above ~20 accounts, the search query passes the ~500 character limit, and you get "not found". There are some solutions to this, which are also required to support the account system in the future, but I'm not sure when I'll have time to work on it. If you're fine with using an RSS client, you can just make multiple multi-feeds.

I see, thanks for the response. How can I get a list of all the people I am following on Twitter by the way? Sorry if this isn't allowed within the same thread, I'm new here.
