### ISSUE TITLE
RasPi (ArmV7) Support

### ISSUE THREAD

**Issue by grubeli** [zedeus/nitter#364]
Nitter build fails with `standard_init_linux.go:211: exec user process caused “exec format error”` error on a Raspberry PI.

As I found on [Internet](https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/4558) reason is an arch.

Coudl you please support armv7?
Raspberry PIs is a very popular solution to self-host services

**Comment by zedeus** [comment]
Is this using the docker image?

**Comment by grubeli** [comment]
Yes

**Comment by megascrapper** [comment]
One workaround I found that works is building the container as `linux/amd64` and emulating it using QEMU. Because of the overhead of emulation it may only be suitable for the Pi 4 and if you're the only one using the instance. 

I've only tested this with the Pi 4 with 8GB ram and 64-bit Pi OS so your mileage may vary.

## Requirements
[docker buildx](https://docs.docker.com/buildx/working-with-buildx/) and [qus](https://github.com/dbhi/qus)

## Building
You may need to run the commands as sudo.

1. Make sure buildx is installed
2. Install and run qus
```
$ docker run --rm --privileged aptman/qus -s -- -p x86_64
```
3. Run `docker buildx ls` and make sure the default builder has `linux/amd64` listed as one of the platforms. So the output file should look like this:
```
NAME/NODE DRIVER/ENDPOINT STATUS  PLATFORMS
default * docker
  default default         running linux/arm64, linux/arm/v7, linux/arm/v6, linux/amd64
```
4. Build and run nitter 
```
$ docker buildx build --platform linux/amd64 -t nitter:latest .
$ docker run -v $(pwd)/nitter.conf:/src/nitter.conf -d -p 8080:8080 --platform linux/amd64 nitter:latest
```
5. Go to localhost:8080 and you should see the nitter homepage. 

Hopefully this helps in the meantime.

**Comment by megascrapper** [comment]
One thing that I still struggle with is how you restart the container once it's stopped for whatever reason. Tried `docker restart nitter` but the container exits immediately with the following error in the log:
```
standard_init_linux.go:219: exec user process caused: exec format error
```
I also tried `docker restart --platform linux/amd64 nitter` only to be greeted with unknown flag.

**Comment by zedeus** [comment]
Docker images for ARM64 and ARMv7 have been added to the readme.
