### ISSUE TITLE
Videos 404

### ISSUE THREAD

**Issue by TheFrenchGhosty** [zedeus/nitter#376]
I guess Twitter changed something, because now all videos 404 on clients.

Nothing seems to get logged by Nitter.

This happens consistently across every instances.

**Comment by llacb47** [comment]
They switched from sending video segments as `ts` segments (HLS) to `m4s` segments (MPEG-DASH or something).

HLS video: `https://nitter.fdn.fr/AlexPattyy/status/1387077145156063234`
MPEG-DASH video: `https://nitter.fdn.fr/NikkiMcR/status/1387151497666965508`

**Comment by decoy-walrus** [comment]
I've put together a fix for my own instance that seems to work. See PR #381 and let me know if it works for you too.

**Comment by jman-schief** [comment]
hi @zedeus last docker image published on hub.docker.com is from 12 days ago, I'm unclear if pr #381 made it into it or not, I /think/ I still experience the issue.

thanks!

**Comment by sethsimmons** [comment]
> hi @zedeus last docker image published on hub.docker.com is from 12 days ago, I'm unclear if pr #381 made it into it or not, I /think/ I still experience the issue.
> 
> thanks!

The latest image was built from that PR:

https://github.com/zedeus/nitter/actions/runs/823410622

If you're running that image you have the fix from #381.

**Comment by jman-schief** [comment]
hm I see. I can see the video linked in this issue, but (for example) not this other one:
https://nitter.fdn.fr/Potse_Berlin/status/1394786474130919427

I'm not sure (didnt really dive into the code yet) but I suspect the culprit might be this `.fmp4` file extension I see in the network traffic? 

cc: @decoy-walrus since author of the patch

**Comment by decoy-walrus** [comment]
Sorry I missed your comment here, spam filter ate it. The post you linked works on my instance of nitter, and a few others I tried like nitter.eu. I'm not sure why it's not loading on your instance. 

Looking at twitter directly, I'm not sure what the `?container=fmp4` parameter on the m3u8 playlist is for. I've only ever seen the video served to me as an mp4 or m4s. 

If I can catch a video that doesn't stream right on my instance I'll be able to dig in more. Twitter seems to roll out changes then roll them back, so this could be a change coming down the pipe.

**Comment by jman-schief** [comment]
thank you @decoy-walrus for the reply! You pushed me to dig deeper into my instance and found that I hadn't rebuilt the container since I dont know when (everytime I feel so stupid for forgetting that)

**Comment by mdemoss** [comment]
I was having an issue where I'd get 404s for video through my nginx proxy but not when bypassing the proxy through SSH port forwarding.

The issue was resolved when I changed `proxy_pass http://127.0.0.1:8080/;` to `proxy_pass http://127.0.0.1:8080;` -- removing the trailing slash.

**Comment by ieure** [comment]
> I was having an issue where I'd get 404s for video through my nginx proxy but not when bypassing the proxy through SSH port forwarding.
> 
> The issue was resolved when I changed `proxy_pass http://127.0.0.1:8080/;` to `proxy_pass http://127.0.0.1:8080;` -- removing the trailing slash.

Thank you for leaving this comment, I had the exact same issue and making that change fixed it for me as well.

I wonder if Nitter could be made more tolerant off this?  I run a half dozen things behind nginx with this same config, and none of them have had a similar problem.

**Comment by jackyzy823** [comment]
@mdemoss @ieure  I encountered  the same issue too.
I found that it is due to if you add "/" in proxy_pass , nginx will decode uri.

https://github.com/zedeus/nitter/blob/73b5b60ac381d3af5e8350bef25757aed0ec9175/src/routes/media.nim#L106-L108

In createMediaRouter route,  nitter expect video URL  like  `/video/(E4EE033E680BA)/(https%3A%2F%2Fvideo.twimg.com)` . so URL is `https%3A%2F%2Fvideo.twimg.com` then nitter do the decode stuff.

however  if you add "/" in proxy_pass  nginx send decode uri to nitter `/video/(E4EE033E680BA/https://video.twimg.com)/(otherstuff)` .so URL is `otherstuff` which  will not pass  `cond "http" in url`. 

Use `base64Media=true` in nitter.conf will mitigate this issue.

I recommend that this should be mentioned in Nitter's nginx wiki part.
