### ISSUE TITLE
Jester route exception

### ISSUE THREAD

**Issue by Mennaruuk** [zedeus/nitter#390]
An error has occured in one of your routes.

Detail: strutils.nim(1315) parseEnum
asyncfutures.nim(372) read
asyncfutures.nim(372) read
asyncfutures.nim(372) read
asyncfutures.nim(372) read
asyncfutures.nim(372) read
Invalid enum value: audiospace

**Comment by c-14** [comment]
I seem to have fixed the issue locally by adding ```audiospace = "audiospace"``` to the CardKind enum in src/types.nim.

A better solution would probably be to add a "fallback" to the CardKind enum which is used in src/parser.nim parseCard whenever parseEnum fails (so that this issue doesn't reappear whenever twitter adds new cards again)
