### ISSUE TITLE
Why did you scrape my content without my permission?

### ISSUE THREAD

**Issue by ljharb** [zedeus/nitter#431]
How do I remove my content from your site?

**Comment by zedeus** [comment]
That mitigation is already in place. What domain did you find?

**Comment by ljharb** [comment]
https://nitter.domain.glass/ljharb

**Comment by zedeus** [comment]
That is not my site, I don't know who operates it and I take no responsibility for it or any other Nitter instance besides nitter.net

**Comment by zedeus** [comment]
Also, no content is "scraped", that's not how Nitter works. I don't understand why you think any of this is an issue, can you explain?

**Comment by ljharb** [comment]
Thanks, i should have clarified in my OP.

It’s clear that you just make the software and aren’t responsible for public sites using it. However, being a proxy on the open web (which you’re not doing, but someone is using your software) is indeed violating a number of things.

This was the only contact link on that site, so i came here, but obviously I’ll need to pursue other avenues. Sorry for the noise.

**Comment by gThorondorsen** [comment]
@ljharb Sorry to continue commenting on the issue, but I really do not understand your mental model here.

Some time ago, Twitter decided that opening things in new tabs was not important enough to support and started reimplementing in JavaScript what could have remained standard `<a>` links. The situation lasted long enough that I looked for alternative presentations to the same content and settled on Nitter (and I have had no reason to look back since). Even though I am not a Twitter user at all, I am regularly linked to the [twitter.com][t] domain with the expectation that I am able to read its content.

What solution would you suggest for people like me who are referred to Twitter content without being Twitter users themselves and can't use the first-party Twitter interface? Is/was the issue that Nitter is displaying content that is available only to (some subset of the) logged in users of Twitter? I have a hard time coming up with reasons why you would want content to be available to everyone visiting [twitter.com][t], *even non-logged in people*, but *not* to people visiting third-party mirrors. Do you have any you can explain here?

[t]: https://twitter.com

**Comment by gojomo** [comment]
> Because i gave Twitter.com permission to host my content; no third party mirrors have permission to host any content; mirrors aren’t allowed to exist.

I'm a third-party observer expressing no opinion on the wisdom or ethics of Nitter's features or some particular website's actions – nor the legality of same (which might hinge on tricky contested matters like interpretation of the DMCA or the enforceability of terms-of-service).

But I'm still curious about the  deeper reasons why you consider 'permission' the crucial precondition here. I could guess (and there have certainly been times that Ive been angry that my writing has been replicated other places without permission), but I'd really like to hear specifics from someone with a different mix of concerns. Why do you prefer that only Twitter Inc display this info to the public, and thus state they have permission, and no one else does? 

Is it the concern someone else might be financially profiting, without providing you a service in return? That the appearance of your name or writings might imply some unintended endorsement, or reflect negatively on your reputation or some economic value of your writings? That mirrors might not delete the content as promptly as Twitter would? Something else? 

Would you have the same concerns if a journalist quoted one or more of your public tweets, in their entirety, in a news article? 

Of course you don't owe anyone any explanation, especially not me - as I'm uninvolved with either this software or site in question, & can't offer any relief in any direction. But these issues come up a lot, across many sites/tools, given that it's fairly easy (nitter or not) for anyone to scrape & mirror info from public places. Broader discussion, understanding, and consensus about when & why it may be tolerable – as for example, simple interface-transformations for a single reader's convenience – and when it may be intolerable – as for example in exploitive, misleading SEO – may help influence future practices.

**Comment by gThorondorsen** [comment]
> There's a number of concerns. If I delete content from twitter, I don't want that content to remain elsewhere; if I block someone on Twitter, I don't want them to easily see that content elsewhere (they'd have to log out of twitter.com otherwise, which is a barrier); if someone googles something where my tweets show up, i want the canonical source to be on twitter.com (multiple canonical sources of content dramatically decreases SEO ranking); etc.

Deletion should not be a problem for Nitter. I've seen countless tweets marked as unavailable, deleted, or outright not found without further information.

Regarding the blocking issue, browsers let you do this regardless of mirror availability. Private windows and tabs are a pretty well-known feature by now and [Firefox](https://github.com/mozilla/multi-account-containers#readme) can do [even more](https://github.com/stoically/temporary-containers).

Thanks for pointing out search engine ranking; I did not consider it and it makes some sense. (Although search engines are not completely blameless IMO.) There are mitigations for that. The first is `robots.txt`, but relies on trusting admins for all instances to set it up correctly (it's reportedly very easy to screw up) and to get search engines to respect it (which they won't if it is screwed up). It's probably what went wrong with the instance you linked previously.

There is also a way for a page to say "my canonical address is elsewhere" (`<link rel="canonical" href="$CANONICAL_URL">` in HTML or `Link: <$CANONICAL_URL>; rel="canonical"` as a HTTP header) which does work cross-domains and seems more robust. (I wish the link to [twitter.com](https://twitter.com) was enough though.) I will open a new issue when I have more time (if someone else wants to do it, feel free).

> Yes, if a journalist quoted one of my public tweets without asking, I'd consider it a similar problem, albeit a bit different because it would be a hand-selected piece of content as opposed to blindly scraping everything i say.
> 
> It's easy to do a lot of things - legal or illegal, ethical or unethical - and I don't particularly care what's easy or legal, since I'm not threatening any consequences. I'm expressing that I find it unethical, as feedback, which obviously folks can take or leave.

The point of my asking for clarifications is that you made assertions that were very confusing to the intended audience of this software without leaving any room for action other than "stop everything", which obviously is very hard when you do not understand what's wrong. I am very glad the discussion can be had (and thanks to @gojomo for chiming in; it probably helped more than the comment I was concurrently drafting) and it seems at least one actionable point has already come out of it.

* * *

> There exists a ton of twitter clients that can provide "convenient" interfaces onto the service for a single user without introducing noise into the public sphere.

In my case, it has to run in the browser because I don't use Twitter so often that I want to install dedicated software (and a browser provides an additional sandboxing level). I want to be able to save my position while branching off a tangent and I know two ways of doing that: by duplicating the tab or by opening a new tab and instantly switching to it. The first one seems to be broken as soon as JavaScript is involved on my browser (may be my browser's fault, not the pages', no idea). For the second one to be usable, loading time should be minimal. That part is very hard to do if the page has to use JavaScript to make additional requests after the page has finished downloading. Nitter's current approach is the sort of implementation I would have reached for naturally.

**Comment by nocturn9x** [comment]
> There's a number of concerns. If I delete content from twitter, I don't want that content to remain elsewhere; if I block someone on Twitter, I don't want them to easily see that content elsewhere (they'd have to log out of twitter.com otherwise, which is a barrier); if someone googles something where my tweets show up, i want the canonical source to be on twitter.com (multiple canonical sources of content dramatically decreases SEO ranking); etc.
> 
> Yes, if a journalist quoted one of my public tweets without asking, I'd consider it a similar problem, albeit a bit different because it would be a hand-selected piece of content as opposed to blindly scraping everything i say.
> 
> It's easy to do a lot of things - legal or illegal, ethical or unethical - and I don't particularly care what's easy or legal, since I'm not threatening any consequences. I'm expressing that I find it unethical, as feedback, which obviously folks can take or leave.
> 
> There exists a ton of twitter clients that can provide "convenient" interfaces onto the service for a single user without introducing noise into the public sphere.

Just so your smooth ape brain realizes, when you post content on any social media platform you give up ownership of said content to those platform. Whatever you post there is now Twitter's, not yours: they're free to do whatever they want with it, including letting you delete it (but it's __not__ illegal not to do so). If Twitter decides scraping is bad and they don't want to allow that, they can surely enforce anti scraping measures: they're a private company after all. But don't come here acting like an entitled ass thinking you have any right to tell others what to do with content you no longer own: I could store all of your account's history, what are you gonna do, sue me? Good luck with that. I have good layers btw, so you can try for sure

**Comment by ljharb** [comment]
@nocturn9x your hostility notwithstanding, twitter’s TOS Grants permission to *twitter* and to nobody else; and the legality depends on the country i live in and the one the site operates in, as well, as on the TOS (the EU has very strong laws on this, far stronger than the US, for example). Scraping doesn’t have to be technically preventable - or even prevented very much - to be illegal or unethical.

i suggest you talk to your good lawyers before telling people on the internet to sue you.

**Comment by zedeus** [comment]
@ljharb Twitter's ToS literally says everyone can do it: 
> This license authorizes us to make your Content available to the rest of the world and to let others do the same.

Note the last part, _let others do the same_. This means _others_, such as Nitter instance operators, are fully allowed to make your content available just like Twitter does, since you gave them the rights to your content.

**Comment by zedeus** [comment]
Section 3 under "Your Rights and Grant of Rights in the Content".
https://twitter.com/en/tos#intlTerms

It states that by submitting your content to Twitter, you grant them a license to display your content, along with everyone else.

**Comment by ljharb** [comment]
To _let_. They have the ability to grant specific permissions to specific people. Nobody else has the permission by default.

**Comment by nocturn9x** [comment]
> @nocturn9x your hostility notwithstanding, twitter’s TOS Grants permission to _twitter_ and to nobody else; and the legality depends on the country i live in and the one the site operates in, as well, as on the TOS (the EU has very strong laws on this, far stronger than the US, for example). Scraping doesn’t have to be technically preventable - or even prevented very much - to be illegal or unethical.
> 
> i suggest you talk to your good lawyers before telling people on the internet to sue you.

Go ahead, I love shitting on twitter SJWs for lolz. People like you make the community hell and deserve to be treated with hostility. Enjoy yourself

**Comment by milahu** [comment]
> People like you make the community hell and deserve to be treated with hostility.

yep, copyright trolls ...

> How do I remove my content from your site?

you mean https://nitter.net/ljharb?

by hiring [professional copyright trolls](https://www.youtube.com/watch?v=KSWqx8goqSY#title=DEFCON%2017:%20That%20Awesome%20Time%20I%20Was%20Sued%20For%20Two%20Billion%20Dollars) and suing the website owner in a court of law.

depending on the owner's jurisdiction, you may get a [friendly answer](https://beebulletin.com/hilarious-pirate-bay-legal-responses/) like ...

> As you may or may not be aware, Sweden is not a state in the United States of America. Sweden is a country in northern Europe. Unless you figured it out by now, US law does not apply here. For your information, **no Swedish law is being violated**. Please be assured that any further contact with us, regardless of medium, will result in a) a suit being filed for harassment b) a formal complaint lodged with the bar of your legal counsel, for sending frivolous legal threats. It is the opinion of us and our lawyers that you are ……. morons, and that you should please go sodomize yourself with retractable batons. Please also note that your e-mail and letter will be published in full on https://www.thepiratebay.org/. Go fuck yourself. Polite as usual, anakata

generally, if you did not suffer any material damage (feelings dont count) which was intentionally caused by the defendant, and if the defendant did not generate any material gain from "your content" (in effect, sell your content for money), then there is no reason to go to court.

but hey, im not a lawyer, and in clown world, anything goes, especially for normies like ljharb.

**Comment by ljharb** [comment]
@milahu i'm not threatening any consequences, nor do i intend to sue anyone. I'm simply providing feedback that it is unethical - that it's a dick move. Lots of dick moves are legal - but a world where people are happy to make dick moves would be a "clown world".

(also, you're clearly not a lawyer because feelings definitely count and are "material" in many court cases, and intentions don't matter either - if i accidentally hit you with my car, that it was an accident doesn't lessen the damage to you)

**Comment by nocturn9x** [comment]
> > > People like you make the community hell and deserve to be treated with hostility.
> > 
> > 
> > 
> > yep, copyright trolls ...
> > 
> > 
> > 
> > > How do I remove my content from your site?
> > 
> > 
> > 
> > you mean https://nitter.net/ljharb?
> > 
> > 
> > 
> > by hiring [professional copyright trolls](https://www.youtube.com/watch?v=KSWqx8goqSY#title=DEFCON%2017:%20That%20Awesome%20Time%20I%20Was%20Sued%20For%20Two%20Billion%20Dollars) and suing the website owner in a court of law.
> > 
> > 
> > 
> > depending on the owner's jurisdiction, you may get a [friendly answer](https://beebulletin.com/hilarious-pirate-bay-legal-responses/) like ...
> > 
> > 
> > 
> > > As you may or may not be aware, Sweden is not a state in the United States of America. Sweden is a country in northern Europe. Unless you figured it out by now, US law does not apply here. For your information, **no Swedish law is being violated**. Please be assured that any further contact with us, regardless of medium, will result in a) a suit being filed for harassment b) a formal complaint lodged with the bar of your legal counsel, for sending frivolous legal threats. It is the opinion of us and our lawyers that you are ……. morons, and that you should please go sodomize yourself with retractable batons. Please also note that your e-mail and letter will be published in full on https://www.thepiratebay.org/. Go fuck yourself. Polite as usual, anakata
> > 
> > 
> > 
> > generally, if you did not suffer any material damage (feelings dont count) which was intentionally caused by the defendant, and if the defendant did not generate any material gain from "your content" (in effect, sell your content for money), then there is no reason to go to court.
> > 
> > 
> > 
> > but hey, im not a lawyer, and in clown world, anything goes, especially for normies like ljharb.
> 
> What's wrong whit you bro? Are you mad? That's crazy bruh 
> 
> Be kind 

Kindness is earned, and you don't earn it by being an insufferable obnoxious troll, hence the heated responses

**Comment by nocturn9x** [comment]
> @milahu i'm not threatening any consequences, nor do i intend to sue anyone. I'm simply providing feedback that it is unethical - that it's a dick move. Lots of dick moves are legal - but a world where people are happy to make dick moves would be a "clown world".
> 
> (also, you're clearly not a lawyer because feelings definitely count and are "material" in many court cases, and intentions don't matter either - if i accidentally hit you with my car, that it was an accident doesn't lessen the damage to you)

If I hit you with my car and rescue you the case is a hell of a lot different than if I had ran off leaving you to die on the sidewalk, so you're again spitting random bullshit. Aside from that, nothing about is unethical, you just have a hilariously warped view of ethics that tickles your gargantuan ego.

**Comment by ljharb** [comment]
@nocturn9x no, it's actually not, you'd still have hit me, and i could still choose to press charges just the same.

My content is mine, which is also the law in the EU in which you live, and it is objectively unethical to distribute my content without my permission.

**Comment by nocturn9x** [comment]
> @nocturn9x no, it's actually not, you'd still have hit me, and i could still choose to press charges just the same.
> 
> My content is mine, which is also the law in the EU in which you live, and it is objectively unethical to distribute my content without my permission.

Even the EU can't protect you if you don't read the privacy policy of the services you use. Now stop whining and let the adults go about their business, please.

**Comment by nocturn9x** [comment]
> @nocturn9x no, it's actually not, you'd still have hit me, and i could still choose to press charges just the same.
> 
> My content is mine, which is also the law in the EU in which you live, and it is objectively unethical to distribute my content without my permission.

Also, just to clarify, I didn't say you wouldn't be able to press charges. I'm saying the case would be different, as would the resulting verdict. Stop twisting my words, dum dum.

**Comment by milahu** [comment]
> i'm not threatening any consequences, nor do i intend to sue anyone. I'm simply providing feedback that it is unethical

yes, youre playing devil's advocate.
sooner or later, a troll with more money will try to sue nitter.net for hurting someone's feelings.

> My content is mine

then dont publish it.

> it is objectively unethical to distribute my content without my permission.

ethics are subjective, not objective.

**Comment by ljharb** [comment]
@milahu publishing it doesn't reduce my ownership, sorry.

**Comment by nocturn9x** [comment]
> @milahu publishing it doesn't reduce my ownership, sorry.

But if you publish it on Twitter, it gives them and us the permission to publish it everywhere else. Just deal with it, it's literally written in their ToS, how cognitively dissonant can an idiot get?
