### ISSUE TITLE
all pic.jpg_name=orig - fix it please

### ISSUE THREAD

**Issue by MiTereKun** [zedeus/nitter#458]
yeah, the site wants to save the pictures not in jpg, but in .jpg_name=orig and every time to delete this crap - it's just annoying. Yes, without this prefix, not the original image opens, but after all, you need to change not even the %addition in the file name%, but to standardize the file format. If you can make a window for uploading files to the site in certain formats, then you can probably do the same for the pictures that the user wants to download.

**Comment by acarasimon96** [comment]
Good catch! This is definitely annoying, and it's something that can be fixed rather quickly. Unfortunately the project has pretty much stalled, so it will take a while before this gets fixed. I would love to work on a PR that fixes this, but right now I'm busy with school.

**Comment by zedeus** [comment]
Not gonna get "fixed" as it's intentional to serve the full resolution.

**Comment by acarasimon96** [comment]
I don't think the submitter meant by be able to change the resolution of the media, and I do like the fact Nitter always serves media in their full resolution. Instead, They were saying that they're having an issue where media would be downloaded with an unrecognized file extension. So, for example, images in JPG format would be saved with a `.jpg_name=orig` extension instead of just `.jpg`.

I'm assuming they're using Windows with file extensions hidden in File Explorer, but nevertheless, it's would be inconvenient (and tedious if they have a lot to save on their devices) for any user to manually change file extensions in the save dialog or in their favorite file manager.

**Comment by zedeus** [comment]
I know, but the only solution I'm aware is removing the resolution query. This is a browser issue, not related to nitter.

**Comment by MiTereKun** [comment]
browser Pale Moon saves in normal resolution pic.jpg_name=orig<b>.jpg</b>. But the browsers based on the chromium do not know how, including mobile opera
one of the sites on which I constantly unload pictures does not understand files
<a><img src="//images.vfl.ru/ii/1636593938/ecc54384/36638325_m.jpg" alt="хнык" title="хнык" border="0"></a>

From solution options - create a JS script that users will need to be downloaded separately, Make a link in about.... And so it would be nice to create a script that over all browsers changes the references to Nitter.net (or the user analog) and Piped

**Comment by zedeus** [comment]
Fixed
