### ISSUE TITLE
Nitter.net is down

### ISSUE THREAD

**Issue by pitsi** [zedeus/nitter#473]
As it is mentioned in the title, nitter.net is down since yesterday (November 30th 2021).
I use its rss feed feature daily in thunderbird and I redirect any twitter links to it via privacy redirect. For now, I have already chosen a different instance that works most of the time, but I would like to know if the main instance is coming back.

Thank you in advance.

**Comment by zedeus** [comment]
Hetzner has locked the IP address due to a couple of DMCA complaints

**Comment by pitsi** [comment]
Just great :( 
Now I have to change the above plus a dozen or more bookmarks to some accounts.

**Comment by zedeus** [comment]
I'll try to get it back up, but can't guarantee when/if it will happen

**Comment by pitsi** [comment]
Why can I reach nitter.net from my phone (android 9, bromite as main browser, via as secondary) but not from my pc (debian x64, brave, chromium unstable and firefox)?
Both of them are connected to the internet through the same router and they both use the same dns (google's dns).

**Comment by zedeus** [comment]
No clue, maybe Hetzner's IP lock isn't doings its job well enough. According to their email I can open a request to unlock it, after "fixing the issue" and providing lots of details. I don't know if I should just open the request and explain the DMCA complaints are likely bogus, or if I should add a hardcoded blacklist for the account in question. 
![image](https://user-images.githubusercontent.com/9434921/144461434-a84be2c9-aa07-43bd-bae7-22d58b59ead4.png)

**Comment by pitsi** [comment]
Stupid people making idiotic requests.
Can't someone access these urls via twitter too? I am no hacker, but I can type the forementioned urls, change nitter.net to twitter.com and still see the contents.
Thus, I think that blacklisting the account in question is perfectly justifiable.

**Comment by zedeus** [comment]
Of course, Nitter is essentially a glorified proxy with no permanent storage (except the username -> ID lookup table). People complaining about it being a mirror and such are just plain wrong. The moment something is gone from Twitter, it will be gone from Nitter itself, and Nitter doesn't manipulate any content.

**Comment by jwh** [comment]
Don't buy from Hetzner, they do this *all of the time* for less

**Comment by MiTereKun** [comment]
and for all this time, not even a single new post in one of the issues. The blocking has already been going on for a very long time, isn't it easier to change the hosting provider? Although, probably, once the project is positioned as a high-quality proxy, then the traffic through the hosting goes through a decent amount, and Hetzner is really one of the cheapest providers.

Is it possible to run the nim site through some crutches on a regular user windows and a static ip?

**Comment by jwh** [comment]
There are other instances, or provide your own

**Comment by Amolith** [comment]
I've dealt with these for months and my (completely un-ideal) solution has been to add webserver redirects back to the home page for whatever URLs they report and just opening hte Hetzner ticket saying something like "access to the material in question has been removed". 

After never having replied to the company sending the ~~spam~~reports, I responded with a rather scathing email last week that essentially said, one, their notice was invalid because Nitter *caches* the media, it doesn't *store* anything, and two, they were actually committing perjury by claiming copyright over material posted to Twitter. I Am Not A Lawyer™, but from my understanding, *Twitter* holds copyright over anything posted on their platform; neither the company sending the DMCA notice ([dmca.pro](https://dmca.pro/)) nor the individual they represent have the legal right to demand I take down the material in the first place.

**Comment by pitsi** [comment]
Nitter.net is working again for me, so I am closing this issue.
Thank you very much for fixing it!

**Comment by pitsi** [comment]
Nitter.net is down for me since almost an hour ago (8pm at gmt+2) and with a 502 error. 
If it is still down by tomorrow, I will reopen the issue.

**Comment by pitsi** [comment]
It is down for me :(
However, I last checked it ~1 hour ago and it was working fine.
