### ISSUE TITLE
Nitter core/maintenance team

### ISSUE THREAD

**Issue by acarasimon96** [zedeus/nitter#502]
I think that the project needs a core team to maintain Nitter, just like with Invidious, NewPipe, and many other large FOSS projects. By having a core team, the project can continue to live on and be better maintained in case @zedeus goes into an extended hiatus again like in most of 2020 and 2021. In addition, having a core team might help with implementing new features and generating ideas for the project in a much faster pace.

Team members should not be required to be knowledgeable with Nim or the undocumented Twitter API, but such requirements are rather recommended and preferred. 

I've been running my own fork, [Nitter FT](https://github.com/acarasimon96/nitter-ft), to add some yet-to-be-merged PRs during that aforementioned hiatus that I think would be useful for my use case. But with Zed's comeback and the flurry of commits these last couple of weeks, it's becoming more difficult for me to maintain my fork. As I'm still highly interested in helping out with the project, I would love to join the team should it ever be formed.

My suggestions for team members other than myself include:
- @jackyzy823 for help with the Twitter API and Nim
- @TheFrenchGhosty, one of the moderators in the Matrix room
- @LainLayer, who apparently has the power to manage issues here

I really want to see this project grow like Invidious and NewPipe; I believe this is one of the things Nitter is lacking to achieve that.

**Comment by TheFrenchGhosty** [comment]
> @TheFrenchGhosty, who's running the Matrix channel

I'm not actually running the Matrix channel, I'm just a moderator there.

I suppose I'm just the most active one in the room since I'm on Matrix everyday for [Invidious](https://invidious.io) and [PussTheCat.org](https://pussthecat.org)

**Comment by acarasimon96** [comment]
Oh, I didn't know that. I'll correct the initial post to take that into account. Thanks for letting me know.

**Comment by zedeus** [comment]
I don't see the point, if people want to contribute they can do so. What is a "core team" in this case? What would it mean to be a team member? It's an open source hobby project, there are no teams. If you're referring to doing things in a more organized way, that's simply infeasible due to external circumstanecs. If someone wants to become a co-maintainer to help manage GitHub issues, write documentation, review PRs, etc. I'm all for it. @LainLayer is a friend of mine that wanted to help out fix a couple bugs and start adding labels to issues, so I gave him repo permissions to do so.

**Comment by acarasimon96** [comment]
In this case, a "core team" would at the very least help maintain the codebase as you mentioned. This is especially useful when you go into a long hiatus again and whenever you feel like spending less time with the project for any reason. You basically covered all the other use cases I could think of, so therefore I would instead call it a "maintenance team" with you as the "benevolent dictator" of the project according to your wishes and desires.

**Comment by jackyzy823** [comment]
Thanks @acarasimon96 

I'm just an ordinary user who hate twitter's auto-reloading page and **login wall** ( few months ago they show it even when i want to view replies , maybe they then rollback this feature).

I use nitter and like it a lot. Since this is an open source project. If there're something i don't like  or i want to improve, I just fork and write code and maybe consider feedbacking to upstream.

Another point for opensource project is that the active fork will be the upstream finally. People will vote with their feet.

**Comment by zedeus** [comment]
Closing this since it's not actionable and everyone is welcome to contribute.
