### ISSUE TITLE
Hide pinned tweets display preference no longer working?

### ISSUE THREAD

**Issue by timreuscher** [zedeus/nitter#532]
Maybe in the last week or so I'm noticing pinned tweets again, even though I have "Hide pinned tweets" enabled in my preferences. Doesn't seem to be browser-specific either, and it does occur in the latest version (f10519c).

Anyone else seeing this?

**Comment by dhoepfl** [comment]
Seeing this, too.

Two potential fixes:

Change src/views/timeline.nim:98 to `if pinned.isSome and not prefs.hidePins:`
or change src/routes/timeline.nim:82 to `var profile = await fetchProfile(after, query, skipPinned=prefs.hidePins)`

Sorry, I cannot test these changes and they are quick shots, as far as I can tell, the problem was introduced by commit 51ae076e.

**Comment by zedeus** [comment]
Fixed, thank you for the suggestions @dhoepfl
