### ISSUE TITLE
Wrong publish date shown

### ISSUE THREAD

**Issue by Perflyst** [zedeus/nitter#65]
For whatever reason I currently get 7:54PM shown while Twitter shows 12:54 PM

Example:
https://twitter.com/3D_director/status/1176223348378001409
https://nitter.snopyta.org/3D_director/status/1176223348378001409

**Comment by zedeus** [comment]
Twitter shows 9:54 PM for me, this comes down to system locales. When I run a nitter instance locally,  get the same date on nitter as I do on Twitter. Best I can do is try to display the timezone, but I'm not sure where to get that information right now.

**Comment by cloudrac3r** [comment]
The only way to get local time in the the browser is either by the server geolocating the IP, or the client using JavaScript, or the page manually asking for the user's timezone.

How I would solve this problem is by serving UTC times from the server, but suppling the unix timestamp in a data attribute, and adding a script that finds elements with timestamps, gets the data attribute, makes a local time string, and writes it back into the element. This would provide local times for people with JavaScript enabled, and fall back to UTC time for users with JavaScript disabled. While this isn't perfect, I think it's the best possible solution.

I would be willing to try to implement this.

**Comment by zedeus** [comment]
All timestamps are now in UTC so it would be possible to have a UTC offset user preference applied server-side, like this

![image](https://user-images.githubusercontent.com/9434921/84473379-410ba280-ac89-11ea-8dec-992ece2ccd75.png)

**Comment by Mennaruuk** [comment]
Is there a way to select this in the settings?

**Comment by zedeus** [comment]
This has not been implemented yet.

**Comment by zedeus** [comment]
I've changed the date formatting from `2:40 AM · Jan 3, 2022` to `Jan 3, 2022 · 2:40 AM UTC` to show that the time is in UTC, thus removing the need for this feature. I still see the value in it, but the "short time" (e.g. `5m`, `7h`, `30 Dec 2021`) displays it relative to UTC so that's correct anyway, and when the short time is changed to a date, the specific time something was posted isn't particularly relevant. In the cases where it is, it's easy to manually convert from UTC.
