### ISSUE TITLE
urgent: nitter.net ssl certificate expiry

### ISSUE THREAD

**Issue by gamer191** [zedeus/nitter#676]
[Nitter.net](https://nitter.net)'s ssl certificate expired 41 minutes ago.
Because HSTS is enabled on nitter.net, this completely prevents people, who have previously accessed Nitter, from accessing Nitter (unless they use an [alternative instance](https://github.com/zedeus/nitter/wiki/Instances)).
See [here](https://www.ssllabs.com/ssltest/analyze.html?d=nitter.net&latest) for more info, and click [here](https://www.ssllabs.com/ssltest/analyze.html?d=nitter.net&clearCache=on) to refresh that page (which takes about 5 minutes)

**Comment by utzer** [comment]
@zedeus did you see this issue about expired SSL certificate on nitter.net?

**Comment by vordenken** [comment]
+1

**Comment by ocdtrekkie** [comment]
I would encourage disabling HSTS, which has the primary effect of disabling the user agent from allowing the user to... access a site with a certificate that expired 41 minutes prior.

Unless there's a significant real world security risk in play, HSTS is a significant antifeature on the web.

**Comment by gamer191** [comment]
@ocdtrekkie HSTS's primary purpose is to warm the user agent if it tries to access the site through unencrypted http, which is usually a result of an MitM doing a downgrade attack. I agree that HSTS warnings should be possible to bypass, subject to the websites discretion (people shouldn't be able to access banks if they are using an expired certificate), but whoever wrote the HSTS standard clearly doesn't agree.

IMO Nitter should continue to use HSTS, to prevent downgrade attacks, because the primary purpose of nitter.net should be to be a secure/private way to use nitter. If someone doesn't care as much about security/privacy, they should use an [alternative instance](https://github.com/zedeus/nitter/wiki/Instances), which shouldn't enable HSTS.

**Comment by ocdtrekkie** [comment]
I've had significant words with one of the coauthors of HSTS. I would argue the ability to cripple user agency makes it a harmful specification, and it should be disregarded until revised to be ethical. (tbh, the entire expired cert behavior is somewhat ridiculous, rather than a hard cutoff, browsers should probably load expired sites with a very visible warning on the address bar for like a week before giving the crazy interstitial warnings we do now... but the authors of these specs do not consider real world scenarios, unfortunately)

Users who wish to ensure HTTPS have the ability to do so via their browser settings/user agent, there's really no need for a site to mandate how my agent acts.
