### ISSUE TITLE
Wrong number of views display

### ISSUE THREAD

**Issue by Perflyst** [zedeus/nitter#68]
I see here https://twitter.com/Reggina_1914/status/1180837350605283328 400 views on Twitter while nitter just display 399?

**Comment by zedeus** [comment]
Videos are cached. Since the view count is the only thing that updates I saw no need to limit how long they're cached. If you check here you can see it's above 400: https://nitter.42l.fr/Reggina_1914/status/1180837350605283328

Personally I don't see this as an issue, as it reduces amount of requests which is important.

**Comment by Perflyst** [comment]
You are right.
