### ISSUE TITLE
RSS gives duplicate feeds - http ones along with https

### ISSUE THREAD

**Issue by Owyn** [zedeus/nitter#693]
I'm a user of nitter.it
Version [2022.08.30-8edfda3](https://github.com/zedeus/nitter/commit/8edfda3)

and once a day or few days all rss entries (from today and from the month ago - all of them) change from https to http and thus give duplicate entries into the reader
![image](https://user-images.githubusercontent.com/1309656/190208256-d2ea85af-0506-49c0-b02c-f560c9b8b5b8.png)

I'm using RSS Guard 4.2.2 reader on win 10 and have tons of  feeds but this issue only happens with nitter ones

**Comment by Owyn** [comment]
Just tried a few more:
 [nitter.pussthecat.org](https://nitter.pussthecat.org/) - it gives https feeds currently, 
 [nitter.42l.fr](https://nitter.42l.fr/) - gives http feeds currently, I think it gonna switch like nitter.it does and give duplicates again some time later, gotta wait to see for sure

**Comment by Owyn** [comment]
so far only nitter.it has been giving dupes (these 3+ days), but not the two above I tried for 3+ days

**Comment by zedeus** [comment]
Sounds like a setup problem with that specific instance then, nothing I can do.

**Comment by Owyn** [comment]
@datanomi seems to be the maintainer of nitter.it - can you look at it, datanomi?

**Comment by datanomi** [comment]
> @datanomi seems to be the maintainer of nitter.it - could you look at it, datanomi?

Hey, thanks for noticing this problem.
 
I was able to replicate the issue by CURLing the rss feed a couple of times and I noticed that sometimes it would return a slightly different feed. 

The issue was one of the servers had a different configuration so it would return a differently formatted feed than the others.

I'm using a reverse proxy to load balance it between 3 servers due to bandwidth limits :D 

The problem should be fixed now.
