### ISSUE TITLE
"Tweet not found" and nothing displaying on profiles

### ISSUE THREAD

**Issue by Arsenal4904** [zedeus/nitter#707]
I have been getting this error and nothing loading on Twitter pages for the last few hours. It hasn't happened for several weeks until it came back today.

**Comment by Arsenal4904** [comment]
Anyone?

**Comment by youridv1** [comment]
I've got the exact same problem. Some profiles still show a pinned tweet or something, but no other tweets

**Comment by escape0707** [comment]
For example https://nitter.net/whyyoutouzhele

**Comment by UserChristie** [comment]
Good afternoon.

I am facing a similar issue. The feed section in handle shows: 'No Items Found'

![638f08fb4f9496617042a6bf](https://user-images.githubusercontent.com/118587076/205871017-fa1072d5-32c3-431f-9481-5afd9070420e.jpg)

**Comment by zedeus** [comment]
Another round of bots: https://github.com/zedeus/nitter/issues/740#issuecomment-1329976896

**Comment by escape0707** [comment]
> Another round of bots: [#740 (comment)](https://github.com/zedeus/nitter/issues/740#issuecomment-1329976896)

When I turn off `Proxy video streaming through the server (might be slow)` option and try to load a tweet with video, Firefox says `No video with supported format and MIME type found`, safari for iOS won't play the vid.

Is that another bug or due to the bot attack and only need to wait, too?

P.S.: I did launch a private windows to test it, so I guess not cache or cookie problem?
