### ISSUE TITLE
Bug: error "User not found" on some instances, works fine on other instances

### ISSUE THREAD

**Issue by ozac** [zedeus/nitter#739]
Twitter user: **thefigen_**
nitter.net (`https://nitter.net/thefigen_`) returns an error: `User "thefigen_" not found`
while other instances, like nitter.it (`https://nitter.it/thefigen_`) are working fine.

This twitter user is active and publishes new content daily.

**Comment by zedeus** [comment]
This seems to have happened because an account which previously had the username was deleted, and now another account has taken the username. The user ID in nitter.net's persistent profile ID lookup table is `1562468976134828033` while the current account's ID is `1562038858988064768`. There only way to prevent this from reoccurring would be to periodically clear out the profile ID tables, but this is likely a very rare event.

For this specific profile I've cleaned out the ID from the table so you can access it again.

**Comment by ozac** [comment]
Thank you!
