### ISSUE TITLE
Add RTL (bidi) support

### ISSUE THREAD

**Issue by ahangarha** [zedeus/nitter#76]
There should be support for RTL languages such as Persian, Arabic, Urdu,...

Currently, all the tweet texts are rendered with LTR direction. This can be done by applying bidi to the project.

![image](https://user-images.githubusercontent.com/11241315/66772659-14b93f80-eeca-11e9-9a95-db925859a313.png)
you may see the current status of Nitter that cannot render RTL text in RTL direction. The first tweet, I have applied the following explanation while the second tweet is following the default Nitter layout.

In quick review, I found that there is a need to add `dir="auto"` to the `div` containing the tweet text and remove the `display: inline` css property from it. I think this would solve the issue but for sure it needs more in depth investigation.

**Comment by zedeus** [comment]
Thank you! I've applied your suggestion and it seems to be working properly.

**Comment by zedeus** [comment]
I spent some time researching the best way to solve this, but unfortunately supporting bidirectional text by default makes clicking tweets quite annoying. The entire text box (including the empty part) blocks clicks, and we don't want `pointer-events: none` since you wouldn't be able to select the text. For these reasons I've put bidi support behind an opt-in preference. If you can come up with a solution that support bidirectional support without blocking click events, I'd be happy to merge it.

**Comment by ahangarha** [comment]
I don't face with any issue!

**Comment by rezad1393** [comment]
this bug is still present
example
https://nitter.pussthecat.org/general_g_e_m
and it is shown correctly in twitter.

**Comment by rezad1393** [comment]
> @rezad1393 did you enable the bidirectional text preference?

didnt see that .
thanks.
