### ISSUE TITLE
Multi twitter feed

### ISSUE THREAD

**Issue by treble2019** [zedeus/nitter#83]
Just wondering if it would be possible to add a feature like

https://nitter.net/thatcks+segphault+troyhunt

so that all these feeds are visible in one page. 

(something like multi-reddit)

**Comment by zedeus** [comment]
This is already possible, just replace the + with commas.
https://nitter.net/thatcks,segphault,troyhunt

**Comment by zedeus** [comment]
Reopened for visibility, it's somewhat a hidden feature.

**Comment by Perflyst** [comment]
You should close it as it is not an issue. There is a search bar and also it could be added as wiki page.

**Comment by dinoturic** [comment]
Is there a limitation in number of account that can be added? Tried with 80 accounts but it didn't show any in the feed

**Comment by zedeus** [comment]
The limitation is due to Twitter's "advanced search" max query length, and circumventing this is non-trivial. They have severe search rate limits where if you go above a certain threshold, tweets older than 10 days don't show up the search. nitter.net has been limited by this for quite a while now, and splitting up multi-feed requests into several requests could trigger this limit for other instances quicker. I've been playing around with automatic proxying, but again this is pretty non-trivial to do properly. As a workaround, you can create a "list" with a throwaway Twitter account, then access it like this:
https://nitter.net/NASA/lists/Astronauts

**Comment by treble2019** [comment]
Generally question: Is it better for nitter server (i.e) lower resources usage - when running lists  like  https://nitter.net/NASA/lists/Astronauts compared to  user1,user2....

**Comment by zedeus** [comment]
It doesn't make a much of a difference. With lists there is no limit to the amount of users, but it requires a Twitter account obviously, and there's no search (for now). With the search you're limited to ~20-25 users
