### ISSUE TITLE
default light theme

### ISSUE THREAD

**Issue by treble2019** [zedeus/nitter#84]
Is there any reason for having default theme as dark? Would it be possible to have something like

https://nitter.net/thatcks?theme=light

(I am not a programmer... )

Thanks for your good work!

**Comment by zedeus** [comment]
Nitter is a little opinionated and I strongly prefer dark themes myself, so that's why, but in the server config admins can set the default theme. I could add a parameter to set the theme like that, but given it only takes a few clicks to change the theme in the settings menu I'm not sure it's worth it

**Comment by Booteille** [comment]
I think it would be useful to include the ability to change the theme in the API once you coded it. So third parties like Invidition could control the theme!

**Comment by zedeus** [comment]
Done, it saves the theme to preferences as well although I'm not sure that's the wanted behaviour, it's an easy fix so let me know if you want that changed.
