### ISSUE TITLE
make icons larger at least for mobile view

### ISSUE THREAD

**Issue by treble2019** [zedeus/nitter#85]
The icons on the top right corner
search, bluebird, i(about), settings.

These are 'really' tiny in android device.
Please make icons larger at least for mobile view

**Comment by zedeus** [comment]
Increased to 16px on mobile, let me know if this is enough

**Comment by zedeus** [comment]
I think what you're asking for was added in #35

**Comment by jstetten** [comment]
Hello.

I know this is an old topic, but I personally feel like this shouldn't be a closed issue. The icons on mobile are still absolutely minuscule and essentially untappable without zooming in every time — no matter the browser or user-agent. 

I mean, here is stock Chrome with zero modifications:

![Nitter.png](https://user-images.githubusercontent.com/398249/165118254-f1c98c14-e8fa-414c-bf6c-094e9452f9f3.png)

Look at all that usable empty space! If you truly feel this is how the site should appear to nearly all users, would you at least consider an option to make everything bigger, (ideally with a custom px field?)

It would be even nicer if this was applied site-wide, because the same could be said about the options page:

![Options.png](https://user-images.githubusercontent.com/398249/165119354-a50502e1-cc0a-42f6-99f0-c03466b200ed.png)

(So much space!) Please let me know if it would be beneficial to open a new issue; a search of old threads shows I'm not the only one.

Either way, it's still a wonderful and needed project. Been using it from it's infancy and am amazed at how much it has grown. Thank you!
