### ISSUE TITLE
Found a bug

### ISSUE THREAD

**Issue by Iskander1220** [zedeus/nitter#876]
Hi! You can see from the links below that some of the tweets are missing because the branch was interrupted due to "This Tweet was deleted by the Tweet author". 

[https://nitter.sethforprivacy.com/Crunchyroll/status/1478199614318821382](https://nitter.sethforprivacy.com/Crunchyroll/status/1478199614318821382)

That is, when a user goes to the title tweet of the branch (id [1478199614318821382](https://nitter.sethforprivacy.com/Crunchyroll/status/1478199614318821382)), he will not see some of the tweets related to the branch, which can be seen here - 

[https://nitter.sethforprivacy.com/Crunchyroll/status/1478399794284761093](https://nitter.sethforprivacy.com/Crunchyroll/status/1478399794284761093)

The reason for this is that Twitter's JSON parsing does not take into account tweets associated with tweets deleted by users.

Sorry my english!

**Comment by pin-grid-array** [comment]
I noticed this problem today when viewing tweets on Twitter dot com itself.

I agree that this branching and deleted-tweet issue is disruptive to the reading experience.

But if Twitter dot com is not displaying the tweets properly, my expectation is that using Nitter will not make the problem go away either.

If you are lucky, sometimes you can find somebody replying to, or quote-retweeting, a tweet further down the branch after the point of the deleted tweet. By going to that tweet that is being replied to, you will see all the tweets further up the branch before it, including the ones prior to the deleted tweet. Unfortunately it's not always possible to find such a tweet.

**Comment by zedeus** [comment]
I'm not sure if the example has changed since you opened this issue, but I don't see the problem you're describing. The branch/thread displays just fine in the second link, and the first one isn't part of a thread so it isn't shown. The first reply in the second link does indeed not show any replies, making it impossible to find the full reply thread, but this behavior is the same for both Nitter and Twitter, so there's not much that can be done.
