### ISSUE TITLE
Remove instance of "Esmail EL BoB"

### ISSUE THREAD

**Issue by MagicLike** [zedeus/nitter#883]
Esmail is actively forbidding members or supporters of the LGBTQIA+ community to use their services via a TOS document*.
This is absolutely queerphobic and extremely discriminating. Therefore I ask to remove their instance `nitter.esmailelbob.xyz` / `invidious.esmail5pdn24shtvieloeedh7ehz3nrwcdivnfhfcedl7gf4kwddhkqd.onion` from the list, to not further support their actions.

*See the commit here: https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a

**Comment by zedeus** [comment]
I'm not taking any stance here. My opinions will not influence the list. Having the site on the community-driven list is not "support", the owner gains nothing from people using the instance regardless.

**Comment by FynhF** [comment]
Not taking any stance here means not taking a stance against clear hate against queer people.
I get it you’re trying to be neutral, but being neutral towards hate and discrimination by letting them stand next to other views is a form of accepting and therefore empowering them, because you’re signaling the discriminators that their stances are as reasonable as others, what they definitely are not.
So maybe you believe that you are not taking a stance, but actually you pretty much are taking one.
